### ISSUE TITLE
运行项目报这个错误是为啥呢？

### ISSUE THREAD

**Issue by giserman001** [dengxiaoning/cesium_dev_kit#9]
![image](https://github.com/dengxiaoning/cesium_dev_kit/assets/24283342/5f196d8d-8b1b-4787-af0e-2c894c0aa22e)

**Comment by giserman001** [comment]
DeveloperError {name: 'DeveloperError', message: 'Expected options.tileWidth to be typeof number, actual typeof was undefined', stack: 'Error\n    at new DeveloperError (http://172.16.50.…dules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1597:17)'}
message
: 
"Expected options.tileWidth to be typeof number, actual typeof was undefined"
name
: 
"DeveloperError"
stack
: 
"Error\n    at new DeveloperError (http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:5961:11)\n    at Check.typeOf.number (http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:6010:11)\n    at new SingleTileImageryProvider (http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:138966:24)\n    at Controller.init (http://172.16.50.13:9527/src/utils/cesiumPluginsExtends/initConf.js:20:33)\n    at new initCesium (http://172.16.50.13:9527/src/utils/cesiumPluginsExtends/indexOld.js:67:27)\n    at Proxy.initMap (http://172.16.50.13:9527/src/views/example/czm/index.vue?t=1712475092343:53:59)\n    at Proxy.mounted (http://172.16.50.13:9527/src/views/example/czm/index.vue?t=1712475092343:7:12)\n    at http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:7056:154\n    at callWithErrorHandling (http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1589:18)\n    at callWithAsyncErrorHandling (http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1597:17)"
[[Prototype]]
: 
Error

**Comment by dengxiaoning** [comment]
> DeveloperError {name: 'DeveloperError', message: 'Expected options.tileWidth to be typeof number, actual typeof was undefined', stack: 'Error\n at new DeveloperError ([http://172.16.50.…dules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1597:17)'}](http://172.16.50.%E2%80%A6dules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1597:17)'%7D) message : "Expected options.tileWidth to be typeof number, actual typeof was undefined" name : "DeveloperError" stack : "Error\n at new DeveloperError ([http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:5961:11)\n](http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:5961:11)%5Cn) at Check.typeOf.number ([http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:6010:11)\n](http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:6010:11)%5Cn) at new SingleTileImageryProvider ([http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:138966:24)\n](http://172.16.50.13:9527/node_modules/.vite/cesium.js?v=cbcc640c:138966:24)%5Cn) at Controller.init ([http://172.16.50.13:9527/src/utils/cesiumPluginsExtends/initConf.js:20:33)\n](http://172.16.50.13:9527/src/utils/cesiumPluginsExtends/initConf.js:20:33)%5Cn) at new initCesium ([http://172.16.50.13:9527/src/utils/cesiumPluginsExtends/indexOld.js:67:27)\n](http://172.16.50.13:9527/src/utils/cesiumPluginsExtends/indexOld.js:67:27)%5Cn) at Proxy.initMap ([http://172.16.50.13:9527/src/views/example/czm/index.vue?t=1712475092343:53:59)\n](http://172.16.50.13:9527/src/views/example/czm/index.vue?t=1712475092343:53:59)%5Cn) at Proxy.mounted ([http://172.16.50.13:9527/src/views/example/czm/index.vue?t=1712475092343:7:12)\n](http://172.16.50.13:9527/src/views/example/czm/index.vue?t=1712475092343:7:12)%5Cn) at [http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:7056:154\n](http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:7056:154%5Cn) at callWithErrorHandling ([http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1589:18)\n](http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1589:18)%5Cn) at callWithAsyncErrorHandling (http://172.16.50.13:9527/node_modules/.vite/chunk-JLZ76TLO.js?v=cbcc640c:1597:17)" [[Prototype]] : Error

我这边测试尚未发现这个异常，你是直接 `git  clone  https://github.com/dengxiaoning/cesium_dev_kit.git ` 后运行的吗？

**Comment by maxiaoqu** [comment]
<img width="314" alt="image" src="https://github.com/dengxiaoning/cesium_dev_kit/assets/25891598/9442da1b-6491-4c52-abb4-f1908b77a8f2">
我的运行起来也是这个错误，菜单没显示出来！node版本从8切换到20都不好使！克隆、直接下载下来也是一样的效果！

**Comment by maxiaoqu** [comment]
![image](https://github.com/dengxiaoning/cesium_dev_kit/assets/25891598/b4df4e97-c864-4855-937d-eb2fd62f4bcc)

**Comment by maxiaoqu** [comment]
> ![image](https://private-user-images.githubusercontent.com/24283342/320260940-5f196d8d-8b1b-4787-af0e-2c894c0aa22e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDY2MzMsIm5iZiI6MTcxMzg0NjMzMywicGF0aCI6Ii8yNDI4MzM0Mi8zMjAyNjA5NDAtNWYxOTZkOGQtOGIxYi00Nzg3LWFmMGUtMmM4OTRjMGFhMjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA0MjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzAxODNmMjZhMDM4ZDM2ZDA4YjMzMmZiZmJhMjNhZjc3ZjUwNGFkZmUwZDg2NTgwOTg5MWVhMTI1NWE4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W0ltHJ6NEVMQ04iE9jH-_JyhpzFqmJLsIflwdDOmvA4)

node的版本：14.16.1，Yarn版本：1.22.10 时可以运行起来，而且正常使用！
